### ISSUE TITLE
Documentation: joinPaths() or joinPath() ?

### ISSUE THREAD

**Issue by jonaswjs** [medialize/URI.js#296]
In the documentation the function is sometimes called `joinPath` and sometimes `joinPaths`.
https://medialize.github.io/URI.js/docs.html#static-joinPath

**Comment by rodneyrehm** [comment]
nice catch! fixed in master.

**Comment by taion** [comment]
Looks like you still have a few places in the docs that say `joinPath()`.

**Comment by rodneyrehm** [comment]
fixed in master, thx.
